export enum EspecialidadesMedico {
  MedicoGeneral = 1,
  Cardiologo = 2,
  Dermatologo = 3,
  Ginecologo = 4,
  Neumologo = 5,
  Neurologo = 6,
  Oncologo = 7,
  Pediatra = 8,
  Psiquiatra = 9,
  Radiologo = 10,
  Traumatologo = 11,
  Urologo = 12,
  Anestesiologo = 13,
  Oftalmologo = 14,
  Otorrinolaringologo = 15,
  Nefrologo = 16,
  Hematologo = 17,
  Gastroenterologo = 18,
  Endocrinologo = 19,
  CirujanoGeneral = 20,
  CirujanoCardiovascular = 21,
  CirujanoPlastico = 22,
  Neurocirujano = 23,
  CirujanoOrtopedico = 24,
}
