INSERT INTO Plantes (CapacitatHabitacions) VALUES (10);
INSERT INTO Plantes (CapacitatHabitacions) VALUES (15);
INSERT INTO Plantes (CapacitatHabitacions) VALUES (20);
INSERT INTO Plantes (CapacitatHabitacions) VALUES (20);
INSERT INTO Plantes (CapacitatHabitacions) VALUES (10);
INSERT INTO Plantes (CapacitatHabitacions) VALUES (10);
INSERT INTO Plantes (CapacitatHabitacions) VALUES (30);
INSERT INTO Plantes (CapacitatHabitacions) VALUES (25);
INSERT INTO Plantes (CapacitatHabitacions) VALUES (5);

INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (101, 1, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (102, 1, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (103, 1, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (104, 1, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (105, 1, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (106, 1, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (107, 1, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (108, 1, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (109, 1, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (201, 2, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (202, 2, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (203, 2, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (204, 2, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (205, 2, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (206, 2, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (207, 2, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (208, 2, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (209, 2, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (301, 3, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (302, 3, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (303, 3, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (304, 3, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (305, 3, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (306, 3, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (307, 3, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (308, 3, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (309, 3, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (310, 3, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (311, 3, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (312, 3, 2);
INSERT INTO Habitacions (CodiHabitacio, PlantaId, CapacitatLlits) VALUES (401, 4, 2);


INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('101A', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '101'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('101B', 1, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '101'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('102A', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '102'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('102B', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '102'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('103A', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '103'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('103B', 1, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '103'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('104A', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '104'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('104B', 1, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '104'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('105A', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '105'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('105B', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '105'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('106A', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '106'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('106B', 1, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '106'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('107A', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '107'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('107B', 1, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '107'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('108A', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '108'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('108B', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '108'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('109A', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '109'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('109B', 1, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '109'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('201A', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '201'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('201B', 1, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '201'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('202A', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '202'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('202B', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '202'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('203A', 0, 1, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '203'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('203B', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '203'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('204A', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '204'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('204B', 1, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '204'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('205A', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '205'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('205B', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '205'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('206A', 0, 1, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '206'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('206B', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '206'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('207A', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '207'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('207B', 1, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '207'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('208A', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '208'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('208B', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '208'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('209A', 0, 1, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '209'));
INSERT INTO Llits (CodiLlit, Ocupat, ForaDeServei, HabitacioId) VALUES ('209B', 0, 0, (SELECT Id FROM Habitacions WHERE CodiHabitacio = '209'));


INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('12345678A', 'ABCD12345678', 'Naruto Uzumaki', 'M');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('23456789B', 'EFGH23456789', 'Sakura Haruno', 'F');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('34567890C', 'IJKL34567890', 'Sasuke Uchiha', 'M');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('45678901D', 'MNOP45678901', 'Kakashi Hatake', 'M');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('56789012E', 'QRST56789012', 'Hinata Hyuga', 'F');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('67890123F', 'UVWX67890123', 'Shikamaru Nara', 'M');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('78901234G', 'YZAB78901234', 'Ino Yamanaka', 'F');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('89012345H', 'CDEF89012345', 'Choji Akimichi', 'M');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('90123456I', 'GHIJ90123456', 'Kiba Inuzuka', 'M');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('01234567J', 'KLMN01234567', 'Shino Aburame', 'M');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('11223344A', 'OPQR11223344', 'Rock Lee', 'M');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('22334455B', 'STUV22334455', 'Neji Hyuga', 'M');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('33445566C', 'WXYZ33445566', 'Tenten', 'F');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('44556677D', 'ABCD44556677', 'Gaara', 'M');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('55667788E', 'EFGH55667788', 'Temari', 'F');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('66778899F', 'IJKL66778899', 'Kankuro', 'M');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('77889900G', 'MNOP77889900', 'Tsunade', 'F');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('88990011H', 'QRST88990011', 'Jiraiya', 'M');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('99001122I', 'UVWX99001122', 'Orochimaru', 'M');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('10020030J', 'YZAB10020030', 'Madara Uchiha', 'M');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('11022033A', 'CDEF11022033', 'Itachi Uchiha', 'M');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('12023034B', 'GHIJ12023034', 'Obito Uchiha', 'M');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('13024035C', 'KLMN13024035', 'Kisame Hoshigaki', 'M');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('14025036D', 'OPQR14025036', 'Deidara', 'M');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('15026037E', 'STUV15026037', 'Sasori', 'M');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('16027038F', 'WXYZ16027038', 'Konan', 'F');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('17028039G', 'ABCD17028039', 'Nagato', 'M');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('18029040H', 'EFGH18029040', 'Hidan', 'M');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('19030041I', 'IJKL19030041', 'Kakuzu', 'M');
INSERT INTO Pacients (DNI, NumSS, Nom, Sexe) VALUES ('20031042J', 'MNOP20031042', 'Zabuza Momochi', 'M');

INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-01-01', '2024-01-10', (SELECT Id FROM Pacients WHERE DNI = '34567890C'), 'Dolor de cabeza', 'Resuelto');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-11-11', '2029-01-10', (SELECT Id FROM Pacients WHERE DNI = '10020030J'), 'Cardiopatia', 'Resuelto');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-03-25', '2024-01-10', (SELECT Id FROM Pacients WHERE DNI = '10020030J'), 'Inmunopatia', 'Resuelto');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-02-20', NULL, (SELECT Id FROM Pacients WHERE DNI = '10020030J'), 'Rotura de ligamentos', 'Estable');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-02-01', '2024-02-02', (SELECT Id FROM Pacients WHERE DNI = '01234567J'), 'Fractura de brazo', 'Resuelto');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-02-01', '2024-11-23', (SELECT Id FROM Pacients WHERE DNI = '01234567J'), 'Rotura Ligamentos', 'Resuelto');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-02-01', '2024-04-21', (SELECT Id FROM Pacients WHERE DNI = '01234567J'), 'Diabetes', 'Resuelto');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-02-01', NULL, (SELECT Id FROM Pacients WHERE DNI = '23456789B'), 'Fractura de brazo', 'Crítico');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-03-01', '2024-03-15', (SELECT Id FROM Pacients WHERE DNI = '34567890C'), 'Gripe', 'Resuelto');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-04-01', NULL, (SELECT Id FROM Pacients WHERE DNI = '45678901D'), 'Dolor de espalda', 'Estable');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-05-01', '2024-05-20', (SELECT Id FROM Pacients WHERE DNI = '56789012E'), 'Alergia', 'Resuelto');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-06-01', NULL, (SELECT Id FROM Pacients WHERE DNI = '67890123F'), 'Hipertensión', 'Estable');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-07-01', '2024-07-10', (SELECT Id FROM Pacients WHERE DNI = '78901234G'), 'Infección urinaria', 'Resuelto');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-08-01', NULL, (SELECT Id FROM Pacients WHERE DNI = '89012345H'), 'Asma', 'Crítico');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-09-01', '2024-09-15', (SELECT Id FROM Pacients WHERE DNI = '90123456I'), 'Conjuntivitis', 'Resuelto');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-10-01', NULL, (SELECT Id FROM Pacients WHERE DNI = '01234567J'), 'Artritis', 'Estable');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-01-05', '2024-01-15', (SELECT Id FROM Pacients WHERE DNI = '11223344A'), 'Migraña', 'Resuelto');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-02-10', NULL, (SELECT Id FROM Pacients WHERE DNI = '22334455B'), 'Dermatitis', 'Crítico');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-03-20', '2024-04-05', (SELECT Id FROM Pacients WHERE DNI = '33445566C'), 'Bronquitis', 'Resuelto');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-04-10', NULL, (SELECT Id FROM Pacients WHERE DNI = '44556677D'), 'Colesterol alto', 'Estable');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-05-15', '2024-06-01', (SELECT Id FROM Pacients WHERE DNI = '55667788E'), 'Otitis', 'Resuelto');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-06-20', NULL, (SELECT Id FROM Pacients WHERE DNI = '66778899F'), 'Dolor abdominal', 'Estable');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-07-05', '2024-07-20', (SELECT Id FROM Pacients WHERE DNI = '77889900G'), 'Esguince de tobillo', 'Resuelto');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-08-10', NULL, (SELECT Id FROM Pacients WHERE DNI = '88990011H'), 'Diabetes', 'Crítico');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-09-15', '2024-09-30', (SELECT Id FROM Pacients WHERE DNI = '99001122I'), 'Gastroenteritis', 'Resuelto');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-10-20', NULL, (SELECT Id FROM Pacients WHERE DNI = '10020030J'), 'Insuficiencia renal', 'Crítico');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2019-11-01', '2020-11-15', (SELECT Id FROM Pacients WHERE DNI = '11022033A'), 'Enfermedad pulmonar', 'Resuelto');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2008-02-11', NULL, (SELECT Id FROM Pacients WHERE DNI = '11022033A'), 'Depresión', 'Estable');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2005-05-26', NULL, (SELECT Id FROM Pacients WHERE DNI = '11022033A'), 'Cejera', 'No Resuelto');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2022-04-30', '2024-11-15', (SELECT Id FROM Pacients WHERE DNI = '11022033A'), 'Colesterol', 'Resuelto');
INSERT INTO EpisodisMedics (DataObertura, DataTancament, PacientId, Dolencia, Estat) VALUES ('2024-12-05', NULL, (SELECT Id FROM Pacients WHERE DNI = '12023034B'), 'Faringitis', 'Estable');


INSERT INTO Personals (DNI, Especialitat, Nom) VALUES ('A1234567A', 'Cirujano', 'Luke Skywalker');
INSERT INTO Personals (DNI, Especialitat, Nom) VALUES ('B2345678B', 'Pediatra', 'Leia Organa');
INSERT INTO Personals (DNI, Especialitat, Nom) VALUES ('C3456789C', 'Enfermero', 'Han Solo');
INSERT INTO Personals (DNI, Especialitat, Nom) VALUES ('D4567890D', 'Dermatólogo', 'Obi-Wan Kenobi');
INSERT INTO Personals (DNI, Especialitat, Nom) VALUES ('E5678901E', 'Oncólogo', 'Yoda');
INSERT INTO Personals (DNI, Especialitat, Nom) VALUES ('F6789012F', 'Psicólogo', 'Darth Vader');
INSERT INTO Personals (DNI, Especialitat, Nom) VALUES ('G7890123G', 'Enfermera', 'Padmé Amidala');
INSERT INTO Personals (DNI, Especialitat, Nom) VALUES ('H8901234H', 'Enfermero', 'Mace Windu');
INSERT INTO Personals (DNI, Especialitat, Nom) VALUES ('I9012345I', 'Urólogo', 'Qui-Gon Jinn');
INSERT INTO Personals (DNI, Especialitat, Nom) VALUES ('J0123456J', 'Neumóloga', 'Rey');

INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('true', 'Severe chest pain', 'Analysis and rest', (SELECT Id FROM Personals WHERE DNI = 'A1234567A'), 3);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('false', 'High fever and cough', NULL, (SELECT Id FROM Personals WHERE DNI = 'B2345678B'), 3);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('true', 'Severe abdominal pain', 'Surgery recommended', (SELECT Id FROM Personals WHERE DNI = 'C3456789C'), 3);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('false', 'Persistent lumbar pain', 'Exercises and physiotherapy', (SELECT Id FROM Personals WHERE DNI = 'D4567890D'), 4);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('true', 'Severe allergic reaction', NULL, (SELECT Id FROM Personals WHERE DNI = 'E5678901E'), 5);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('false', 'High blood pressure', 'Antihypertensive medication', (SELECT Id FROM Personals WHERE DNI = 'F6789012F'), 6);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('true', 'Serious infection', 'Intravenous antibiotics', (SELECT Id FROM Personals WHERE DNI = 'G7890123G'), 7);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('false', 'Difficulty breathing', 'Inhalers and follow-up', (SELECT Id FROM Personals WHERE DNI = 'H8901234H'), 8);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('true', 'Asthmatic crisis', 'Steroids and monitoring', (SELECT Id FROM Personals WHERE DNI = 'I9012345I'), 9);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('false', 'Joint pain', 'Anti-inflammatories and therapy', (SELECT Id FROM Personals WHERE DNI = 'J0123456J'), 10);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('true', 'Severe dehydration', 'Intravenous rehydration', (SELECT Id FROM Personals WHERE DNI = 'A1234567A'), 11);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('false', 'Mild sprain', 'Rest and bandaging', (SELECT Id FROM Personals WHERE DNI = 'B2345678B'), 12);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('true', 'Intense nasal bleeding', 'Cauterization and treatment', (SELECT Id FROM Personals WHERE DNI = 'C3456789C'), 13);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('false', 'Sore throat', 'Antibiotics and gargles', (SELECT Id FROM Personals WHERE DNI = 'D4567890D'), 14);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('true', 'Compound fracture', 'Surgery and cast', (SELECT Id FROM Personals WHERE DNI = 'E5678901E'), 15);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('false', 'Severe insomnia', 'Medication and therapy', (SELECT Id FROM Personals WHERE DNI = 'F6789012F'), 5);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('true', 'Diabetic ketoacidosis', 'Insulin and fluids', (SELECT Id FROM Personals WHERE DNI = 'G7890123G'), 3);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('false', 'Mild colitis', 'Diet and medication', (SELECT Id FROM Personals WHERE DNI = 'H8901234H'), 4);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('true', 'Food poisoning', 'Detoxification and fluids', (SELECT Id FROM Personals WHERE DNI = 'I9012345I'), 5);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('false', 'Sinusitis', 'Decongestants and analgesics', (SELECT Id FROM Personals WHERE DNI = 'J0123456J'), 10);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('true', 'Hypertensive crisis', 'Antihypertensive medication and monitoring', (SELECT Id FROM Personals WHERE DNI = 'A1234567A'), 5);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('false', 'Arm bruise', 'Rest and ice', (SELECT Id FROM Personals WHERE DNI = 'B2345678B'), 8);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('true', 'Acute chest pain', 'Urgent cardiac evaluation', (SELECT Id FROM Personals WHERE DNI = 'C3456789C'), 9);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('false', 'Nausea and vomiting', 'Anti-emetics and fluids', (SELECT Id FROM Personals WHERE DNI = 'D4567890D'), 4);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('true', 'Severe infection', 'Intravenous antibiotics and observation', (SELECT Id FROM Personals WHERE DNI = 'E5678901E'), 15);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('false', 'Chronic fatigue', 'Exams and lifestyle changes', (SELECT Id FROM Personals WHERE DNI = 'F6789012F'), 16);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('true', 'Severe allergic reaction', 'Adrenaline and monitoring', (SELECT Id FROM Personals WHERE DNI = 'G7890123G'), 17);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('false', 'Muscle tension', 'Massage and stretching', (SELECT Id FROM Personals WHERE DNI = 'H8901234H'), 18);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('true', 'Severe respiratory infection', 'Antibiotics and oxygen', (SELECT Id FROM Personals WHERE DNI = 'I9012345I'), 9);
INSERT INTO Consultes (Urgencia, Sintomatologia, Recepta, PersonalId, EpisodiMedicId) VALUES ('false', 'Joint pain', 'Anti-inflammatories and physical therapy', (SELECT Id FROM Personals WHERE DNI = 'J0123456J'), 14);

INSERT INTO Ingressos (DataEntrada, DataSortida, EpisodiMedicId, LlitId) VALUES ('2024-01-01', '2024-01-10', 4, (SELECT Id FROM Llits WHERE CodiLlit = '101A'));
INSERT INTO Ingressos (DataEntrada, DataSortida, EpisodiMedicId, LlitId) VALUES ('2024-02-01', NULL, 4, (SELECT Id FROM Llits WHERE CodiLlit = '202B'));
INSERT INTO Ingressos (DataEntrada, DataSortida, EpisodiMedicId, LlitId) VALUES ('2024-03-01', '2024-03-15', 3, (SELECT Id FROM Llits WHERE CodiLlit = '203A'));
INSERT INTO Ingressos (DataEntrada, DataSortida, EpisodiMedicId, LlitId) VALUES ('2024-04-01', NULL, 4, (SELECT Id FROM Llits WHERE CodiLlit = '204B'));
INSERT INTO Ingressos (DataEntrada, DataSortida, EpisodiMedicId, LlitId) VALUES ('2024-05-01', '2024-05-20', 5, (SELECT Id FROM Llits WHERE CodiLlit = '105A'));
INSERT INTO Ingressos (DataEntrada, DataSortida, EpisodiMedicId, LlitId) VALUES ('2024-06-01', NULL, 6, (SELECT Id FROM Llits WHERE CodiLlit = '106B'));
INSERT INTO Ingressos (DataEntrada, DataSortida, EpisodiMedicId, LlitId) VALUES ('2024-07-01', '2024-07-10', 7, (SELECT Id FROM Llits WHERE CodiLlit = '107A'));
INSERT INTO Ingressos (DataEntrada, DataSortida, EpisodiMedicId, LlitId) VALUES ('2024-08-01', NULL, 8, (SELECT Id FROM Llits WHERE CodiLlit = '108B'));
INSERT INTO Ingressos (DataEntrada, DataSortida, EpisodiMedicId, LlitId) VALUES ('2024-09-01', '2024-09-15', 9, (SELECT Id FROM Llits WHERE CodiLlit = '109A'));
INSERT INTO Ingressos (DataEntrada, DataSortida, EpisodiMedicId, LlitId) VALUES ('2024-10-01', NULL, 10, (SELECT Id FROM Llits WHERE CodiLlit = '201A'));
